# for streamlit deployment

# for wheat page
wheat:
  model_path: saved_models/wheat # path to saved pycaret's pipeline, omit .pkl extension since pycaret load_model appends it for us

  # interface text
  interface:
    page_title: Wheat Kernel Classifier
    page_icon: üåæ

  # features
  model:
    features: [Area, Perimeter, Compactness, Length, Width, AsymmetryCoeff, Groove]
    features_desc:
      - Area of the Kernel
      - Perimeter of the Kernel
      - Measure of Kernel Compactness
      - Length of the Kernel
      - Width of the Kernel
      - Asymmetry Coefficient of the Kernel
      - Length of Kernel Groove

    # default inputs on interface for wheat model
    # same order as wheat.features
    features_default:
      - 11.84
      - 13.21
      - 0.85
      - 5.18
      - 2.84
      - 3.6
      - 5.04

  # id to human labels (map numeric indices to class names)
  id2label: [Kama, Rosa, Canadian]

  # file path to dummy data for user to download
  demo_data_fp: data/demo/wheat.csv


# for melbourne page
melbourne:
  model_path: saved_models/melbourne # path to saved pycaret's pipeline, omit .pkl extension since pycaret load_model appends it for us

  # interface text
  interface:
    page_title: Melbourne Residential Pricing Predictor
    page_icon: üè†

  # features
  model:
    features: [Rooms, Distance, Landsize, BuildingArea, YearBuilt, Type, Method, Region, Bathroom, Car, Lattitude, Longtitude, Propertycount, YearSold, MonthSold, Suburb]
    pred_log_path: src/streamlit/logs/melbourne_pred_log.csv

    # key: features.lower()
    features_range:
      rooms:
        default: 3
        range: [1, 10] # inclusive
        step: 1
        help: "Number of rooms"
      distance:
        default: 10.0
        range: [0.0, 50.0]
        step: 0.1
        help: "km to CBD"
      landsize:
        default: 300.0
        range: [0.0, 2000.0]
        step: 1.0
        help: "Land size"
      buildingarea:
        default: 150.0
        range: [0.0, 1000.0]
        step: 1.0
        help: "Building size"
      yearbuilt:
        default: 1995
        range: [1850, 2025]
        step: 1
        help: "Year in which property was built"
      type:
        default: "h"
        choices: ["h", "t", "u"]
        help: "h - house, cottage, villa, semi, terrace; t - townhouse; u - unit, duplex"
      method:
        default: "S"
        choices: ["S", "SP", "PI", "VB"]
        help: "S - property sold; SP - property sold prior; PI - property passed in; VB - vendor bid"
      region:
        default: "Northern Metropolitan"
        choices:
          - "Northern Metropolitan"
          - "Western Metropolitan"
          - "Southern Metropolitan"
          - "Eastern Metropolitan"
        help: "Region of property"
      bathroom:
        default: 1
        range: [0, 10]
        step: 1
        help: "Number of bathrooms"
      car:
        default: 1
        range: [0, 8]
        step: 1
        help: "Number of parking spots for cars"
      lattitude:
        default: -37.80
        range: [-90.0, 90.0]
        step: 0.0001
        format: "%.4f"
        help: "Latitude of property"
      longtitude:
        default: 144.96
        range: [-180.0, 180.0]
        step: 0.0001
        format: "%.4f"
        help: "Longtitude of property"
      propertycount:
        default: 5000
        range: [0, 100000]
        step: 10
        help: "Number of properties that exist in  the suburb"
      yearsold:
        default: 2017
        range: [2007, 2025]
        step: 1
        help: "Year of sale date"
      monthsold:
        default: 7
        range: [1, 12]
        step: 1
        help: "Month of sale date"
      suburb:
        default: "Abbotsford"
        help: "Suburb of the residential property"



# for used car prices page
used_car_prices:
  model_path: saved_models/used_car_prices

  # interface text
  interface:
    page_title: Used Car Price Predictor
    page_icon: üöó

  # interface custom styling (path to file that contains the style element)
  custom_styling_fp: src/streamlit/assets/used_car_prices.html

  # file path of train metrics
  train_metrics_fp: src/streamlit/assets/used_car_prices_training_metrics.json

  # features
  model:
    features: [Location, Kilometers_Driven, Fuel_Type, Transmission, Owner_Type, Seats, Mileage_km_kg, Power_bhp, Car_Age]
    cat_cols: [Location, Fuel_Type, Transmission, Owner_Type]
    int_cols: [Kilometers_Driven, Seats, Car_Age]
    float_cols: [Mileage_km_kg, Power_bhp]

    # key: features.lower()
    features_range:
      location:
        default: Mumbai
        choices: [Mumbai, Hyderabad, Kochi, Coimbatore, Pune, Delhi, Kolkata, Chennai, Jaipur, Bangalore, Ahmedabad]
      kilometers_driven:
        default: 50000
        range: [0]
        step: 100
      fuel_type:
        default: Petrol
        choices: [Petrol, Diesel, CNG, LPG, Electric]
      transmission:
        default: Manual
        choices: [Manual, Automatic, Other]
      owner_type:
        default: First
        choices: [First, Second, Third, Fourth & Above]
      seats:
        default: 5
        choices: [2, 4, 5, 6, 7, 8, 9]
      mileage_km_kg:
        default: 18
        range: [0]
      power_bhp:
        default: 90
        range: [0]
      car_age:
        default: 10
        range: [0]
        step: 1
